config/routes.rb
HerokuSanDemo::Application.routes.draw do
  resources :droids

end

app/models/droid.rb
class Droid < ActiveRecord::Base
  validates_uniqueness_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/droids_controller.rb
class DroidsController < ApplicationController
  # GET /droids
  # GET /droids.xml
  def index
    @droids = Droid.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @droids }
      format.text  { render :text => @droids.sort_by(&:name).map(&:name).join(", ") }
    end
  end

  # GET /droids/1
  # GET /droids/1.xml
  def show
    @droid = Droid.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @droid }
    end
  end

  # GET /droids/new
  # GET /droids/new.xml
  def new
    @droid = Droid.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @droid }
    end
  end

  # GET /droids/1/edit
  def edit
    @droid = Droid.find(params[:id])
  end

  # POST /droids
  # POST /droids.xml
  def create
    @droid = Droid.new(params[:droid])

    respond_to do |format|
      if @droid.save
        format.html { redirect_to(@droid, :notice => 'Droid was successfully created.') }
        format.xml  { render :xml => @droid, :status => :created, :location => @droid }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @droid.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /droids/1
  # PUT /droids/1.xml
  def update
    @droid = Droid.find(params[:id])

    respond_to do |format|
      if @droid.update_attributes(params[:droid])
        format.html { redirect_to(@droid, :notice => 'Droid was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @droid.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /droids/1
  # DELETE /droids/1.xml
  def destroy
    @droid = Droid.find(params[:id])
    @droid.destroy

    respond_to do |format|
      format.html { redirect_to(droids_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/droids_helper.rb
module DroidsHelper
end

app/views/droids/_form.html.erb
<%= form_for(@droid) do |f| %>
  <% if @droid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@droid.errors.count, "error") %> prohibited this droid from being saved:</h2>

      <ul>
      <% @droid.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/droids/edit.html.erb
<h1>Editing droid</h1>

<%= render 'form' %>

<%= link_to 'Show', @droid %> |
<%= link_to 'Back', droids_path %>

app/views/droids/index.html.erb
<h1>Listing droids</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @droids.each do |droid| %>
  <tr>
    <td><%= droid.name %></td>
    <td><%= link_to 'Show', droid %></td>
    <td><%= link_to 'Edit', edit_droid_path(droid) %></td>
    <td><%= link_to 'Destroy', droid, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Droid', new_droid_path %>

app/views/droids/new.html.erb
<h1>New droid</h1>

<%= render 'form' %>

<%= link_to 'Back', droids_path %>

app/views/droids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @droid.name %>
</p>


<%= link_to 'Edit', edit_droid_path(@droid) %> |
<%= link_to 'Back', droids_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HerokuSanDemo</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>